#language: node_js
#node_js:
#  - 8
sudo: required
services:
  - docker

before_install:
  - docker build -t fxabreu/docker-react -f Dockerfile.dev .

script:
 # - docker run fxabreu/docker-react npm cache clear
 # - docker run -e CI=true fxabreu/docker-react npm run test
  - docker run -e CI=true fxabreu/docker-react npm run test -- --coverage
 
