language: node_js
node_js:
  - 10
sudo: required
services:
  - docker

before_install:
  - docker build -t fxabreu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true fxabreu/docker-react npm run test -- --coverage
